---

- name: Add group
  group:
    name: solr
    state: present

- name: Add user
  user:
    name: solr
    state: present
    group: solr
    shell: /bin/bash

- name: Download solr tgz
  get_url:
    url: http://ftp.jaist.ac.jp/pub/apache/lucene/solr/7.6.0/solr-7.6.0.tgz
    dest: /opt/solr-7.6.0.tgz
    mode: 0440

- name: Unarchive solr7
  unarchive:
    src: /opt/solr-7.6.0.tgz
    dest: /opt
    remote_src: yes
    creates: /opt/solr-7.6.0
    group: solr
    owner: solr
    mode: 0766
  become: yes
  
- name: Install solr as service
  command: bash install_solr_service.sh /opt/solr-7.6.0.tgz
  args:
    chdir: /opt/solr-7.6.0/bin
    creates: /etc/init.d/solr
  become: yes
